#!/bin/bash
### Timestamped logs/rotate
#
# Author: Franck Jouvanceau

_log_help() {
    printf '%s\n' '
usage: [<vars>] autologsh [--nolog] <command>|- [<args>]
with vars default:
  logfile=~/.autolog/<command>.log or autologsh.log for -
  maxsize=5M nrotate=4
  timeformat=[%Y-%m-%d %H:%M:%S]
'
}

_log_rotate() {
    export PATH=$PATH:/usr/sbin
    cat - <<EOF >"$logconf"
$logfile {
    maxsize $maxsize
    rotate $nrotate
    compress
    copytruncate
}
EOF
    logrotate -s "$logconf.s" "$logconf"
    maxs=${maxsize%[kKM]}
    case "$maxsize" in
      *[kK]) ((maxs*=1024));;
      *M)    ((maxs*=1024*1024));;
    esac
}

_log_ts() {
    awk '{print strftime(tf), $0; fflush() }' tf="$timeformat"
}

_log_ts_rot() {
    typeset size=$(stat -c '%s' "$logfile")
    awk -f <(printf '%s' '
         { o=strftime(tf)" "$0;print o;fflush();s+=length(o)+1 }
         s>m{s=0;system("logrotate -s "lc".s "lc" &")}
    ') tf="$timeformat" lc="$logconf" s=$size m=$maxs
}

_log_out() {
    if ((log));then
        if ((out))
        then _log_ts_rot |tee -a "$logfile" 
        else _log_ts_rot >>"$logfile"
        fi
    else _log_ts
    fi
}

function do_log {
    typeset logdir logfile="$logfile" timeformat="${timeformat:-[%Y-%m-%d %H:%M:%S]}" cmd log=1
    typeset maxsize="${maxsize:-5M}" maxs nrotate="${nrotate:-4}" logconf out=1
    [ "$1" = --nolog ] && log=0 && shift
    [ "$1" = --noout ] && out=0 && shift
    ((log)) && {
        [ "$1" ] && [ "$1" != '-' ] && : ${logfile:=~/.autolog/"$1".log}
        : ${logfile:=~/.autolog/"${0##*/}".log}
        logdir="${logfile%/*}"
        [ "$logdir" = "$logfile" ] && logdir='.'
        mkdir -p "$logdir" || return 1
        touch "$logfile" || return 1
        [[ $logfile = /* ]] || logfile="$(cd $logdir;pwd -P)/${logfile##*/}"
        logconf="${logdir}/.${logfile##*/}.conf"
        _log_rotate
        echo '---------------------------------' >>"$logfile"
    }
    [ "$1" = "-" ] && { _log_out; return; }
    if [ "$1" ] ;then _log_out < <("$@" 2>&1)
    else exec > >(_log_out) 2>&1
    fi
}

function log {
    typeset logformat="${logformat:-%-5s %-10s %s\n}"
    printf "$logformat" "$@"
}
#enable -f /usr/lib/bash/tee tee 2>/dev/null
[[ "$1" = -*h* ]] && _log_help || do_log "$@"
